{{- if and .Values.agent.enabled (not .Values.agent.existingSecret) .Values.agent.secretValues }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mqdeck.fullname" . }}-agent
  labels:
    {{- include "mqdeck.componentLabels" (dict "root" . "component" "agent") | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.agent.secretValues }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
{{- if and .Values.api.enabled (not .Values.api.existingSecret) .Values.api.secretValues }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mqdeck.fullname" . }}-api
  labels:
    {{- include "mqdeck.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.api.secretValues }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
{{- if and .Values.web.enabled (not .Values.web.existingSecret) .Values.web.secretValues }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mqdeck.fullname" . }}-web
  labels:
    {{- include "mqdeck.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.web.secretValues }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
