global:
  elasticsearch:
    url: https://elasticsearch.example.com:9200

worker:
  enabled: true
  existingConfigMap: mqdeck-worker-config
  existingSecret: mqdeck-worker-secrets

api:
  enabled: false

web:
  enabled: false
