apiVersion: v2
name: mqdeck
description: Install MQDeck Agent, API, and Web components independently or together.
type: application
version: 1.0.6
appVersion: "1.0.6"
home: https://github.com/mqdeck/mqdeck
sources:
  - https://github.com/mqdeck/mqdeck
keywords:
  - ibmmq
  - rabbitmq
  - observability
  - messaging
maintainers:
  - name: MQDeck
